# Generated by Django 5.2.6 on 2025-10-25 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_add_video_synthesis_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerDiarizationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(0-100)')),
                ('message', models.TextField(blank=True, verbose_name='当前消息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('num_speakers_detected', models.IntegerField(blank=True, null=True, verbose_name='检测到的说话人数量')),
                ('total_segments', models.IntegerField(blank=True, null=True, verbose_name='总字幕片段数')),
                ('total_faces', models.IntegerField(blank=True, null=True, verbose_name='检测到的人脸总数')),
                ('valid_faces', models.IntegerField(blank=True, null=True, verbose_name='高质量人脸数')),
                ('clustering_params', models.JSONField(blank=True, default=dict, verbose_name='聚类参数')),
                ('filter_statistics', models.JSONField(blank=True, default=dict, verbose_name='过滤统计')),
                ('vlm_trace_id', models.CharField(blank=True, max_length=200, verbose_name='VLM Trace ID')),
                ('llm_trace_id', models.CharField(blank=True, max_length=200, verbose_name='LLM Trace ID')),
                ('is_applied', models.BooleanField(default=False, verbose_name='是否已应用')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='应用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarization_tasks', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '说话人识别任务',
                'verbose_name_plural': '说话人识别任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_id', models.IntegerField(verbose_name='说话人ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='姓名')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='角色')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='性别')),
                ('face_count', models.IntegerField(default=0, verbose_name='人脸数量')),
                ('segment_count', models.IntegerField(default=0, verbose_name='出现片段数')),
                ('segments', models.JSONField(default=list, verbose_name='出现的片段编号列表')),
                ('appearance', models.JSONField(blank=True, default=dict, verbose_name='外貌特征')),
                ('character_analysis', models.JSONField(blank=True, default=dict, verbose_name='性格分析')),
                ('representative_images', models.JSONField(default=list, verbose_name='代表人脸图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='speakers.speakerdiarizationtask', verbose_name='识别任务')),
            ],
            options={
                'verbose_name': '说话人档案',
                'verbose_name_plural': '说话人档案',
                'ordering': ['speaker_id'],
            },
        ),
        migrations.AddIndex(
            model_name='speakerdiarizationtask',
            index=models.Index(fields=['project', '-created_at'], name='speakers_sp_project_98cfad_idx'),
        ),
        migrations.AddIndex(
            model_name='speakerdiarizationtask',
            index=models.Index(fields=['status'], name='speakers_sp_status_288200_idx'),
        ),
        migrations.AddIndex(
            model_name='speakerprofile',
            index=models.Index(fields=['task', 'speaker_id'], name='speakers_sp_task_id_8b5364_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakerprofile',
            unique_together={('task', 'speaker_id')},
        ),
    ]
