# Generated by Django 5.2.7 on 2025-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='avg_confidence',
            field=models.FloatField(default=0.0, verbose_name='平均置信度'),
        ),
        migrations.AlterField(
            model_name='speakerdiarizationtask',
            name='llm_trace_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='LLM Trace ID'),
        ),
        migrations.AlterField(
            model_name='speakerdiarizationtask',
            name='vlm_trace_id',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='VLM Trace ID'),
        ),
    ]
