# Generated by Django 5.2.7 on 2025-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_speakerprofile_avg_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerdiarizationtask',
            name='llm_trace_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LLM Trace ID'),
        ),
        migrations.AlterField(
            model_name='speakerdiarizationtask',
            name='vlm_trace_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VLM Trace ID'),
        ),
    ]
