# Generated by Django 5.2.6 on 2025-09-18 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=200)),
                ('source_lang', models.CharField(choices=[('zh', '中文'), ('yue', '粤语'), ('en', '英语'), ('es', '西班牙语'), ('fr', '法语'), ('ru', '俄语'), ('de', '德语'), ('pt', '葡萄牙语'), ('ar', '阿拉伯语'), ('it', '意大利语'), ('ja', '日语'), ('ko', '韩语'), ('id', '印尼语'), ('vi', '越南语'), ('tr', '土耳其语'), ('nl', '荷兰语'), ('uk', '乌克兰语'), ('th', '泰语'), ('pl', '波兰语'), ('ro', '罗马尼亚语'), ('el', '希腊语'), ('cs', '捷克语'), ('fi', '芬兰语'), ('hi', '印地语'), ('bg', '保加利亚语'), ('da', '丹麦语'), ('he', '希伯来语'), ('ms', '马来语'), ('fa', '波斯语'), ('sk', '斯洛伐克语'), ('sv', '瑞典语'), ('hr', '克罗地亚语'), ('fil', '菲律宾语'), ('hu', '匈牙利语'), ('no', '挪威语'), ('sl', '斯洛文尼亚语'), ('ca', '加泰罗尼亚语'), ('nn', '尼诺斯克语'), ('ta', '泰米尔语'), ('af', '阿非利卡语')], default='zh', help_text='源语言', max_length=10)),
                ('target_lang', models.CharField(choices=[('zh', '中文'), ('yue', '粤语'), ('en', '英语'), ('es', '西班牙语'), ('fr', '法语'), ('ru', '俄语'), ('de', '德语'), ('pt', '葡萄牙语'), ('ar', '阿拉伯语'), ('it', '意大利语'), ('ja', '日语'), ('ko', '韩语'), ('id', '印尼语'), ('vi', '越南语'), ('tr', '土耳其语'), ('nl', '荷兰语'), ('uk', '乌克兰语'), ('th', '泰语'), ('pl', '波兰语'), ('ro', '罗马尼亚语'), ('el', '希腊语'), ('cs', '捷克语'), ('fi', '芬兰语'), ('hi', '印地语'), ('bg', '保加利亚语'), ('da', '丹麦语'), ('he', '希伯来语'), ('ms', '马来语'), ('fa', '波斯语'), ('sk', '斯洛伐克语'), ('sv', '瑞典语'), ('hr', '克罗地亚语'), ('fil', '菲律宾语'), ('hu', '匈牙利语'), ('no', '挪威语'), ('sl', '斯洛文尼亚语'), ('ca', '加泰罗尼亚语'), ('nn', '尼诺斯克语'), ('ta', '泰米尔语'), ('af', '阿非利卡语')], default='en', help_text='目标语言', max_length=10)),
                ('srt_file_path', models.FileField(blank=True, help_text='SRT文件路径', null=True, upload_to='srt/')),
                ('video_file_path', models.FileField(blank=True, help_text='视频文件路径', null=True, upload_to='videos/')),
                ('tts_model', models.CharField(default='speech-01-turbo', help_text='TTS模型', max_length=50)),
                ('voice_mappings', models.JSONField(default=dict, help_text='角色音色映射表')),
                ('custom_vocabulary', models.JSONField(default=list, help_text='专有词汇表')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-updated_at'],
            },
        ),
    ]
