# Generated by Django 5.2.6 on 2025-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='voice_mappings',
            field=models.JSONField(default=list, help_text='角色音色映射表'),
        ),
    ]
