# Generated by Django 5.2.6 on 2025-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_voice_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_lang',
            field=models.CharField(choices=[('Chinese', '中文'), ('Chinese,Yue', '粤语'), ('English', '英语'), ('Spanish', '西班牙语'), ('French', '法语'), ('Russian', '俄语'), ('German', '德语'), ('Portuguese', '葡萄牙语'), ('Arabic', '阿拉伯语'), ('Italian', '意大利语'), ('Japanese', '日语'), ('Korean', '韩语'), ('Indonesian', '印尼语'), ('Vietnamese', '越南语'), ('Turkish', '土耳其语'), ('Dutch', '荷兰语'), ('Ukrainian', '乌克兰语'), ('Thai', '泰语'), ('Polish', '波兰语'), ('Romanian', '罗马尼亚语'), ('Greek', '希腊语'), ('Czech', '捷克语'), ('Finnish', '芬兰语'), ('Hindi', '印地语'), ('Bulgarian', '保加利亚语'), ('Danish', '丹麦语'), ('Hebrew', '希伯来语'), ('Malay', '马来语'), ('Persian', '波斯语'), ('Slovak', '斯洛伐克语'), ('Swedish', '瑞典语'), ('Croatian', '克罗地亚语'), ('Filipino', '菲律宾语'), ('Hungarian', '匈牙利语'), ('Norwegian', '挪威语'), ('Slovenian', '斯洛文尼亚语'), ('Catalan', '加泰罗尼亚语'), ('Nynorsk', '尼诺斯克语'), ('Tamil', '泰米尔语'), ('Afrikaans', '阿非利卡语')], default='Chinese', help_text='源语言', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_lang',
            field=models.CharField(choices=[('Chinese', '中文'), ('Chinese,Yue', '粤语'), ('English', '英语'), ('Spanish', '西班牙语'), ('French', '法语'), ('Russian', '俄语'), ('German', '德语'), ('Portuguese', '葡萄牙语'), ('Arabic', '阿拉伯语'), ('Italian', '意大利语'), ('Japanese', '日语'), ('Korean', '韩语'), ('Indonesian', '印尼语'), ('Vietnamese', '越南语'), ('Turkish', '土耳其语'), ('Dutch', '荷兰语'), ('Ukrainian', '乌克兰语'), ('Thai', '泰语'), ('Polish', '波兰语'), ('Romanian', '罗马尼亚语'), ('Greek', '希腊语'), ('Czech', '捷克语'), ('Finnish', '芬兰语'), ('Hindi', '印地语'), ('Bulgarian', '保加利亚语'), ('Danish', '丹麦语'), ('Hebrew', '希伯来语'), ('Malay', '马来语'), ('Persian', '波斯语'), ('Slovak', '斯洛伐克语'), ('Swedish', '瑞典语'), ('Croatian', '克罗地亚语'), ('Filipino', '菲律宾语'), ('Hungarian', '匈牙利语'), ('Norwegian', '挪威语'), ('Slovenian', '斯洛文尼亚语'), ('Catalan', '加泰罗尼亚语'), ('Nynorsk', '尼诺斯克语'), ('Tamil', '泰米尔语'), ('Afrikaans', '阿非利卡语')], default='English', help_text='目标语言', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='tts_model',
            field=models.CharField(default='speech-2.5-hd-preview', help_text='TTS模型', max_length=50),
        ),
    ]
