# Generated by Claude Code migration
from django.db import migrations


def migrate_language_codes_forward(apps, schema_editor):
    """将旧的语言代码转换为新的英文名称"""
    Project = apps.get_model('projects', 'Project')

    # 旧代码到新英文名称的映射
    code_to_english = {
        'zh': 'Chinese',
        'yue': 'Chinese,Yue',
        'en': 'English',
        'es': 'Spanish',
        'fr': 'French',
        'ru': 'Russian',
        'de': 'German',
        'pt': 'Portuguese',
        'ar': 'Arabic',
        'it': 'Italian',
        'ja': 'Japanese',
        'ko': 'Korean',
        'id': 'Indonesian',
        'vi': 'Vietnamese',
        'tr': 'Turkish',
        'nl': 'Dutch',
        'uk': 'Ukrainian',
        'th': 'Thai',
        'pl': 'Polish',
        'ro': 'Romanian',
        'el': 'Greek',
        'cs': 'Czech',
        'fi': 'Finnish',
        'hi': 'Hindi',
        'bg': 'Bulgarian',
        'da': 'Danish',
        'he': 'Hebrew',
        'ms': 'Malay',
        'fa': 'Persian',
        'sk': 'Slovak',
        'sv': 'Swedish',
        'hr': 'Croatian',
        'fil': 'Filipino',
        'hu': 'Hungarian',
        'no': 'Norwegian',
        'sl': 'Slovenian',
        'ca': 'Catalan',
        'nn': 'Nynorsk',
        'ta': 'Tamil',
        'af': 'Afrikaans',
    }

    for project in Project.objects.all():
        # 转换source_lang
        if project.source_lang in code_to_english:
            project.source_lang = code_to_english[project.source_lang]

        # 转换target_lang
        if project.target_lang in code_to_english:
            project.target_lang = code_to_english[project.target_lang]

        project.save()


def migrate_language_codes_backward(apps, schema_editor):
    """将英文名称转换回旧的语言代码"""
    Project = apps.get_model('projects', 'Project')

    # 英文名称到旧代码的映射
    english_to_code = {
        'Chinese': 'zh',
        'Chinese,Yue': 'yue',
        'English': 'en',
        'Spanish': 'es',
        'French': 'fr',
        'Russian': 'ru',
        'German': 'de',
        'Portuguese': 'pt',
        'Arabic': 'ar',
        'Italian': 'it',
        'Japanese': 'ja',
        'Korean': 'ko',
        'Indonesian': 'id',
        'Vietnamese': 'vi',
        'Turkish': 'tr',
        'Dutch': 'nl',
        'Ukrainian': 'uk',
        'Thai': 'th',
        'Polish': 'pl',
        'Romanian': 'ro',
        'Greek': 'el',
        'Czech': 'cs',
        'Finnish': 'fi',
        'Hindi': 'hi',
        'Bulgarian': 'bg',
        'Danish': 'da',
        'Hebrew': 'he',
        'Malay': 'ms',
        'Persian': 'fa',
        'Slovak': 'sk',
        'Swedish': 'sv',
        'Croatian': 'hr',
        'Filipino': 'fil',
        'Hungarian': 'hu',
        'Norwegian': 'no',
        'Slovenian': 'sl',
        'Catalan': 'ca',
        'Nynorsk': 'nn',
        'Tamil': 'ta',
        'Afrikaans': 'af',
    }

    for project in Project.objects.all():
        # 转换source_lang
        if project.source_lang in english_to_code:
            project.source_lang = english_to_code[project.source_lang]

        # 转换target_lang
        if project.target_lang in english_to_code:
            project.target_lang = english_to_code[project.target_lang]

        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_source_lang_alter_project_target_lang_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_language_codes_forward, migrate_language_codes_backward),
    ]