# Generated by Django 5.2.6 on 2025-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_migrate_language_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='concatenated_audio_url',
            field=models.CharField(blank=True, help_text='拼接后的完整音频URL', max_length=500),
        ),
    ]
