# Generated by Django 5.2.6 on 2025-09-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_concatenated_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_speed',
            field=models.FloatField(default=2.0, help_text='TTS时间戳对齐允许的最大speed参数，范围1.2-2.0'),
        ),
    ]
