# Generated by Django 5.2.6 on 2025-10-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_max_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_info',
            field=models.TextField(blank=True, default='', help_text='对话背景信息，用于辅助LLM分配说话人'),
        ),
    ]
