# Generated by Django 5.2.6 on 2025-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_background_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num_speakers',
            field=models.IntegerField(default=2, help_text='对话中的角色数量，用于LLM自动分配说话人'),
        ),
    ]
