# Generated by Django 5.2.6 on 2025-10-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_num_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_audio_path',
            field=models.FileField(blank=True, help_text='分离后的背景音', null=True, upload_to='audio/background/'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_audio_path',
            field=models.FileField(blank=True, help_text='从视频提取的原始音频', null=True, upload_to='audio/original/'),
        ),
        migrations.AddField(
            model_name='project',
            name='separation_completed_at',
            field=models.DateTimeField(blank=True, help_text='分离完成时间', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='separation_started_at',
            field=models.DateTimeField(blank=True, help_text='分离开始时间', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='separation_status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '分离中'), ('completed', '已完成'), ('failed', '失败')], default='pending', help_text='人声分离状态', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='vocal_audio_path',
            field=models.FileField(blank=True, help_text='分离后的人声音频', null=True, upload_to='audio/vocals/'),
        ),
    ]
