# Generated by Django 5.2.6 on 2025-10-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_background_audio_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_video_path',
            field=models.FileField(blank=True, help_text='最终合成视频路径', null=True, upload_to='videos/final/'),
        ),
        migrations.AddField(
            model_name='project',
            name='mixed_audio_path',
            field=models.FileField(blank=True, help_text='混合音频路径（翻译+背景）', null=True, upload_to='audio/mixed/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='concatenated_audio_url',
            field=models.CharField(blank=True, help_text='拼接后的完整翻译音频URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_file_path',
            field=models.FileField(blank=True, help_text='原始视频文件路径', null=True, upload_to='videos/'),
        ),
    ]
