# Generated by Django 5.2.6 on 2025-10-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_video_synthesis_fields'),
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_diarization_task',
            field=models.ForeignKey(blank=True, help_text='当前使用的说话人识别任务', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_projects', to='speakers.speakerdiarizationtask'),
        ),
    ]
