# Generated by Django 5.2.7 on 2025-10-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_current_diarization_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background_info',
        ),
        migrations.RemoveField(
            model_name='project',
            name='num_speakers',
        ),
    ]
