# Generated by Django 5.2.6 on 2025-09-22 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_translate_request_interval', models.FloatField(default=1.0, help_text='控制批量翻译API请求之间的间隔时间，范围：0.1-10秒', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='批量翻译请求间隔（秒）')),
                ('max_concurrent_translate_tasks', models.IntegerField(default=3, help_text='系统同时运行的批量翻译任务数量限制，范围：1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='最大并发翻译任务数')),
                ('task_timeout_minutes', models.IntegerField(default=60, help_text='批量翻译任务的最长执行时间，范围：5-300分钟', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='任务超时时间（分钟）')),
                ('enable_detailed_logging', models.BooleanField(default=True, help_text='记录批量翻译的详细执行日志', verbose_name='启用详细日志')),
                ('auto_cleanup_completed_tasks', models.BooleanField(default=True, help_text='自动清理已完成或失败的任务数据', verbose_name='自动清理完成的任务')),
                ('cleanup_interval_hours', models.IntegerField(default=24, help_text='自动清理任务的间隔时间，范围：1-168小时', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)], verbose_name='清理间隔（小时）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='TaskMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('task_type', models.CharField(default='batch_translate', max_length=50, verbose_name='任务类型')),
                ('project_id', models.IntegerField(verbose_name='项目ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('timeout', '超时')], default='pending', max_length=20, verbose_name='状态')),
                ('total_segments', models.IntegerField(default=0, verbose_name='总段落数')),
                ('completed_segments', models.IntegerField(default=0, verbose_name='已完成段落数')),
                ('failed_segments', models.IntegerField(default=0, verbose_name='失败段落数')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('current_segment_text', models.TextField(blank=True, verbose_name='当前处理段落')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务监控',
                'verbose_name_plural': '任务监控',
                'ordering': ['-created_at'],
            },
        ),
    ]
