# Generated by Django 5.2.6 on 2025-09-22 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='batch_tts_request_interval',
            field=models.FloatField(default=2.0, help_text='控制批量TTS API请求之间的间隔时间，范围：0.5-20秒', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(20.0)], verbose_name='批量TTS请求间隔（秒）'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='max_concurrent_tts_tasks',
            field=models.IntegerField(default=2, help_text='系统同时运行的批量TTS任务数量限制，范围：1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='最大并发TTS任务数'),
        ),
        migrations.AddField(
            model_name='taskmonitor',
            name='alignment_details',
            field=models.JSONField(blank=True, default=dict, help_text='时间戳对齐过程的详细信息', verbose_name='对齐详情'),
        ),
        migrations.AddField(
            model_name='taskmonitor',
            name='current_step',
            field=models.CharField(blank=True, help_text='如：第2步：LLM优化', max_length=100, verbose_name='当前步骤'),
        ),
        migrations.AddField(
            model_name='taskmonitor',
            name='silent_segments',
            field=models.IntegerField(default=0, help_text='时间戳对齐失败设为静音的段落数', verbose_name='静音段落数'),
        ),
    ]
