# Generated by Django 5.2.6 on 2025-11-11 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0002_systemconfig_batch_tts_request_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='cleanup_execution_time',
            field=models.TimeField(default='03:00:00', help_text='每天执行数据清理的时间（建议凌晨时段）', verbose_name='清理执行时间'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='cleanup_projects_after_days',
            field=models.IntegerField(default=1, help_text='删除N天未更新的项目及其所有关联数据，范围：1-365天', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='项目清理天数'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='cleanup_users_after_days',
            field=models.IntegerField(default=7, help_text='删除N天未登录的普通用户及其所有数据（不删除超级管理员），范围：1-365天', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='用户清理天数'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='enable_auto_cleanup_data',
            field=models.BooleanField(default=False, help_text='定期清理不活跃的项目和用户数据（谨慎开启）', verbose_name='启用数据自动清理'),
        ),
    ]
