# Generated by Django 5.2.6 on 2025-09-24 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_time', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('total_count', models.IntegerField(verbose_name='查询到的音色总数')),
                ('system_voice_count', models.IntegerField(default=0, verbose_name='系统音色数量')),
                ('voice_cloning_count', models.IntegerField(default=0, verbose_name='音色克隆数量')),
                ('voice_generation_count', models.IntegerField(default=0, verbose_name='音色生成数量')),
                ('success', models.BooleanField(default=True, verbose_name='查询是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '音色查询日志',
                'verbose_name_plural': '音色查询日志',
                'ordering': ['-query_time'],
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=200, unique=True, verbose_name='音色ID')),
                ('voice_name', models.CharField(blank=True, max_length=200, verbose_name='音色名称')),
                ('voice_type', models.CharField(choices=[('system_voice', '系统音色'), ('voice_cloning', '音色克隆'), ('voice_generation', '音色生成')], max_length=20, verbose_name='音色类型')),
                ('description', models.JSONField(blank=True, default=list, verbose_name='描述')),
                ('user_note', models.TextField(blank=True, verbose_name='用户备注')),
                ('created_time', models.CharField(max_length=20, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '音色',
                'verbose_name_plural': '音色',
                'ordering': ['-created_at'],
                'unique_together': {('voice_id', 'user')},
            },
        ),
    ]
