# Generated by Django 5.2.6 on 2025-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='voice_id',
            field=models.CharField(max_length=200, verbose_name='音色ID'),
        ),
    ]
