# Generated by Django 5.2.6 on 2025-09-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='段落序号')),
                ('start_time', models.FloatField(help_text='开始时间(秒)')),
                ('end_time', models.FloatField(help_text='结束时间(秒)')),
                ('speaker', models.CharField(default='SPEAKER_00', help_text='说话人', max_length=50)),
                ('original_text', models.TextField(help_text='原文本')),
                ('translated_text', models.TextField(blank=True, help_text='翻译文本')),
                ('voice_id', models.CharField(blank=True, help_text='音色ID', max_length=100)),
                ('emotion', models.CharField(choices=[('auto', '自动'), ('happy', '高兴'), ('sad', '悲伤'), ('angry', '愤怒'), ('fearful', '恐惧'), ('disgusted', '厌恶'), ('surprised', '惊讶'), ('calm', '平静')], default='auto', help_text='情绪参数', max_length=20)),
                ('speed', models.FloatField(default=1.0, help_text='语速参数(0.5-2.0)')),
                ('original_audio_url', models.URLField(blank=True, help_text='原音频URL')),
                ('translated_audio_url', models.URLField(blank=True, help_text='翻译音频URL')),
                ('t_tts_duration', models.FloatField(blank=True, help_text='TTS音频时长(秒)', null=True)),
                ('target_duration', models.FloatField(blank=True, help_text='目标时长(秒)', null=True)),
                ('ratio', models.FloatField(blank=True, help_text='时长比例(T_tts/目标时长)', null=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('translating', '翻译中'), ('translated', '已翻译'), ('tts_processing', 'TTS处理中'), ('completed', '已完成'), ('failed', '失败'), ('silent', '静音')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='projects.project')),
            ],
            options={
                'verbose_name': '段落',
                'verbose_name_plural': '段落',
                'ordering': ['project', 'index'],
                'unique_together': {('project', 'index')},
            },
        ),
    ]
