# Generated by Django 5.2.6 on 2025-09-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='segment',
            name='speed',
            field=models.FloatField(default=1.0, help_text='语速参数(0-2.0]'),
        ),
    ]
