# Generated by Django 5.2.6 on 2025-09-24 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCloneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=200, verbose_name='音色ID')),
                ('clone_audio_file_id', models.CharField(max_length=200, verbose_name='克隆音频文件ID')),
                ('prompt_audio_file_id', models.CharField(blank=True, max_length=200, verbose_name='Prompt音频文件ID')),
                ('prompt_text', models.TextField(blank=True, verbose_name='Prompt文本')),
                ('test_text', models.TextField(verbose_name='试听文本')),
                ('model', models.CharField(default='speech-2.5-hd-preview', max_length=50, verbose_name='试听模型')),
                ('need_noise_reduction', models.BooleanField(default=False, verbose_name='是否开启降噪')),
                ('need_volume_normalization', models.BooleanField(default=False, verbose_name='是否开启音量归一化')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('demo_audio_url', models.URLField(blank=True, verbose_name='试听音频URL')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('api_response', models.JSONField(blank=True, null=True, verbose_name='API响应')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '音色克隆记录',
                'verbose_name_plural': '音色克隆记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
