# Generated by Django 5.2.6 on 2025-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_cloning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceclonerecord',
            name='trace_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Trace ID'),
        ),
    ]
