# Generated by Django 5.2.6 on 2025-09-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_cloning', '0002_voiceclonerecord_trace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceclonerecord',
            name='clone_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_clone/clone_audio/', verbose_name='克隆音频文件'),
        ),
        migrations.AddField(
            model_name='voiceclonerecord',
            name='demo_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_clone/demo_audio/', verbose_name='试听音频文件'),
        ),
        migrations.AddField(
            model_name='voiceclonerecord',
            name='prompt_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_clone/prompt_audio/', verbose_name='Prompt音频文件'),
        ),
    ]
