# Generated by Django 5.2.6 on 2025-09-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='group_id',
            field=models.CharField(help_text='MiniMax Group ID', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'group_id')},
        ),
    ]
