# Generated by Django 5.2.6 on 2025-10-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_update_user_model_for_multi_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='dashscope_api_key',
            field=models.CharField(blank=True, help_text='阿里云DashScope API Key（用于ASR语音识别生成SRT，格式：sk-xxx）', max_length=100, null=True),
        ),
    ]
