# Generated by Django 5.2.6 on 2025-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_update_user_model_for_multi_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_access_key_id',
            field=models.CharField(blank=True, help_text='阿里云AccessKey ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_access_key_secret',
            field=models.CharField(blank=True, help_text='阿里云AccessKey Secret', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_app_key',
            field=models.CharField(blank=True, help_text='阿里云ASR AppKey', max_length=100, null=True),
        ),
    ]
