# Generated by Django 5.2.7 on 2025-10-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userconfig_dashscope_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_access_key_id',
            field=models.CharField(blank=True, help_text='阿里云AccessKey ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_access_key_secret',
            field=models.CharField(blank=True, help_text='阿里云AccessKey Secret', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_app_key',
            field=models.CharField(blank=True, help_text='阿里云智能语音应用Key（APP_KEY）', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='aliyun_asr_appkey',
            field=models.CharField(blank=True, help_text='阿里云ASR应用Key（备用）', max_length=100, null=True),
        ),
    ]
